### ISSUE TITLE
Issue in building the application version 2.0

### ISSUE THREAD

**Issue by gouravsachdeva** [hisptz/idashboard#50]
Hello Team,

I am trying to use an application interactive Dashboard. I found the code from the given link "https://github.com/hisptz/idashboard/tree/2.0". I want to change within the code but whenever I tried to build/compile the code using "ng build"/"ng serve" I am getting some modules can't found a type of error attached below.

I am using following versions...

Node Version: v8.11.3
angular/CLI Version: 1.1.1
npm Version: 6.1.0

ERROR :

ERROR in ../idashboard/src/app/dashboard/providers/visualization.service.ts (4,32): Cannot find module '../../map/providers/legend-set.service'.

ERROR in ../idashboard/src/app/dimensions/components/org-unit-filter/org-unit-filter.component.ts (93,57): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/dimensions/components/org-unit-filter/org-unit-filter.component.ts (105,32): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/dimensions/components/org-unit-filter/org-unit-filter.component.ts (118,32): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/app.module.ts (27,26): Cannot find module './menu/menu.module'.

ERROR in ../idashboard/src/app/app.module.ts (47,25): Cannot find module './map/map.module'.

ERROR in ../idashboard/src/app/dashboard/components/dashboard-item-card/dashboard-item-card.component.ts (22,28): Cannot find module '../../../map/map.component'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (40,34): Cannot find module '../period-filter/period-filter.module'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (43,32): Cannot find module '../data-filter/data-filter.module'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (48,28): Cannot find module '../map/map.component'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (49,36): Cannot find module '../map/components/map-template/map-template.component'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (50,33): Cannot find module '../map/components/map-table/map-table.component'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (51,34): Cannot find module '../map/components/map-loader/map-loader.component'.

ERROR in ../idashboard/src/app/dashboard/dashboard.module.ts (52,44): Cannot find module '../map/components/visualization-legend/visualization-legend.component'.

ERROR in ../idashboard/src/app/orgunit-filter/providers/orgunit.service.ts (35,57): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/orgunit-filter/providers/orgunit.service.ts (46,32): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/orgunit-filter/providers/orgunit.service.ts (58,32): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in Error encountered resolving symbol values statically. Could not resolve ./menu/menu.module relative to ../idashboard/src/app/app.module.ts., resolving symbol AppModule in ../idashboard/src/app/app.module.ts, resolving symbol AppModule in ../idashboard/src/app/app.module.ts

ERROR in ../idashboard/src/app/app.module.ts (27,26): Cannot find module './menu/menu.module'.

ERROR in ../idashboard/src/app/app.module.ts (47,25): Cannot find module './map/map.module'.

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './menu/menu.module' in 'D:\Intpart Work\Interactive Dashboard\2.0\idashboard\src\app'
 @ ./src/app/app.module.ts 32:0-48
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './map/map.module' in 'D:\Intpart Work\Interactive Dashboard\2.0\idashboard\src\app'
 @ ./src/app/app.module.ts 50:0-45
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ../idashboard/src/app/dashboard/providers/visualization.service.ts (4,32): Cannot find module '../../map/providers/legend-set.service'.

ERROR in ./src/app/dashboard/providers/visualization.service.ts
Module not found: Error: Can't resolve '../../map/providers/legend-set.service' in 'D:\Intpart Work\Interactive Dashboard\2.0\idashboard\src\app\dashboard\providers'
 @ ./src/app/dashboard/providers/visualization.service.ts 12:0-74
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ../idashboard/src/app/dimensions/components/org-unit-filter/org-unit-filter.component.ts (93,57): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/dimensions/components/org-unit-filter/org-unit-filter.component.ts (105,32): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

ERROR in ../idashboard/src/app/dimensions/components/org-unit-filter/org-unit-filter.component.ts (118,32): Property 'TOGGLE_SELECTED_MULTI' does not exist on type '{ TOGGLE_ACTIVE: (tree: TreeModel, node: TreeNode, $event: any) => TreeNode; TOGGLE_ACTIVE_MULTI:...'.

**Comment by rajey** [comment]
Hello Georav
While we are at it may I advice trying out our latest release https://github.com/hisptz/idashboard/releases/tag/v2.1.0-beta.11

We will provided you with clear instructions for running and change whatever you want in the code

**Comment by gouravsachdeva** [comment]
Hello @rajey ,

Sure, I can work with the given version. If you can provide me the instructions for running.

**Comment by rajey** [comment]
Hello @gouravsachdeva ,

Link I sent has the zipped file ready for deploying to DHIS2 system. 

On related note, I have updated Read me file in the source with all necessary instructions for setting up and running the app, please look into it in branch named `2.1` since that is current stable and actively supported.

**Comment by gouravsachdeva** [comment]
hello @rajey 

I did the stuff mentioned in the above link but the code is not getting compiled yet. It's throwing an error mentioned below... Kindly give me some solution for this..



ERROR: 

ERROR in src/app/app.module.ts(25,28): error TS2307: Cannot find module './modules/menu/menu.module'.
src/app/app.module.ts(51,29): error TS2307: Cannot find module './modules/chart/chart.module'.
src/app/app.module.ts(54,29): error TS2307: Cannot find module './modules/table/table.module'.
src/app/pages/dashboard/components/visualization-list/visualization-card/visualization-card.component.ts(8,36): error TS2307: Cannot find module '../../../../../modules/chart/components/chart-list/chart-list.component'.
src/app/pages/dashboard/components/visualization-list/visualization-card/visualization-card.component.ts(9,36): error TS2307: Cannot find module '../../../../../modules/table/components/table-list/table-list.component'.

**Comment by rajey** [comment]
Hello @gouravsachdeva , have you run this comman ` npm run setup`?

**Comment by gouravsachdeva** [comment]
Hello @rajey,
Yes, I run that command which is throwing an error:

ERROR:

>npm run setup
npm ERR! missing script: setup
npm ERR! A complete log of this run can be found in:
npm ERR!     ..\AppData\Roaming\npm-cache\_logs\2018-06-29T04_00_29_523Z-debug.log

**Comment by rajey** [comment]
Hello @gouravsachdeva 

It is my hope that you cloned repository

`git clone https://github.com/hisptz/idashboard.git`

Then after everything is fully downloaded then, you checkout to branch `2.1` which as I said previously is the most stable one

`git checkout 2.1`

Then on successfully switch, I assume now you follow the installation instruction, but to summarize

`npm run setup`

then

`npm start` which will start application in `http://localhost:4200`

Can you confirm that this is what you did?

**Comment by gouravsachdeva** [comment]
Hello @rajey 

if I have to work with version 2.0 as it is compatible with Dhis2 Version 2.28. Can you please tell me that how can I build it?

as I run the following commands...

npm install --save-dev @angular/cli@1.1.1
ng serve

And this is not working it's throwing some kind of errors.
